apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-06-16T21:35:26Z"
  generation: 1
  labels:
    app: test-deployment
  name: test-deployment
  namespace: default
  resourceVersion: "9568"
  uid: 3d5d54c6-8a70-4f7e-860b-666ebb02c425
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-deployment
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
